"""editor revisions

Revision ID: 01e2a6b69547
Revises: 431fad7763be
Create Date: 2018-04-23 12:34:38.435605

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column
from sqlalchemy import String, Binary, Integer, Text

# revision identifiers, used by Alembic.
revision = '01e2a6b69547'
down_revision = '431fad7763be'
branch_labels = None
depends_on = None

pages = table(
    'pages',
    column('id', Binary),
    column('title', String),
    column('content', String),
    column('pagetype', Text),
    column('updated_by', String))

def upgrade():
    op.drop_table('pages')
    op.create_table('pages',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.Text(length=40000), nullable=False),
    sa.Column('pagetype', sa.String(length=16), nullable=False),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )

    op.bulk_insert(pages,
    [{'id': lifeloopweb.db.utils.generate_guid().bytes,
        'title': "<h2 class='mt-5' style='box-sizing: border-box; margin-bottom: 0.5rem; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important;'>TONEO, INC. PRIVACY STATEMENT</h2>",
        'content': """
                    <p class='mt-3' style='box-sizing: border-box; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif; margin-top: 1rem !important;'>Toneo, Inc., believes that protecting your privacy is a serious issue that we as an organization take very seriously. Please read the Privacy Policy (the 'Policy') to learn more about what measures Toneo, Inc., takes to insure your information is secured. This Policy describes what information Toneo, Inc., and our product website (Lifeloop.live) collects from you and what happens to that information once gathered by us. This Policy applies to to all sites under Lifeloop.live domain as well our platform, tools and services ('Platform Services').</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>1. INFORMATION COLLECTED</h4>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.1.</span>&nbsp;We collect the following information about you and your use of our Platform Services in order to create a better experience for you:</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.1.1.</span>&nbsp;Basic user profile information.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.1.2.</span>&nbsp;For each Lifeloop.live group, a name of the group will be assigned by the group leader and statement or short description which will be viewed by everyone accessing the specific Lifeloop.live group.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.1.3.</span>&nbsp;For purposes of this Policy,Personally Identifiable Information (PII) describes information that could be used to identity you personally (such as email address, user name, IP address, DOB, sex, marital status, type of employment, # of children, city, zip code, religious affiliation) which has not been previously disclosed by you and the public areas of the website or the messages you send to groups in the Lifeloop.live Platform.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.2.</span>&nbsp;We automatically track basic information about our members (Internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, click patterns, etc.) Lifeloop.live will use this information to provide us with internal research on our member's usage patterns, demographics, interests and general behavior to provide you a better experience with building your community with Lifeloop.live Platform Services.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.3.</span>&nbsp;We do collect information,(postings, conversations, materials) that is provided during individual group sessions within the Platform. The Platform also uses an instant messenger system that will allow you to communicate with other members in the group. Lifeloop.live will archive the messaging history as a way to ensure that there is a record of the communication as well as to comply with any current judicial proceeding, court order or legal process that is served upon our Platform.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.4.</span>&nbsp;We currently contract and utilize online partners to provide the business and communication services for building your community. To do this we and our partners use third-party tracking technologies such as web beacons, pixels, and cookies on the Lifeloop.live Platform. A cookie is a piece of data stored on your computer that is tied to information about you. This type of information collected included the URL you came from and go to, your browser information, and IP address. These cookies further help us to learn and to improve our service to you. Lifeloop.live uses these technologies for user authentication, tracking the user, records the number of group sessions, preferences, and movements in the Platform. Lifeloop.live also utilizes this information for anonymous and aggregate marketing analytics, performance analytics, ad retargeting, and tracking aggregate trends on the Platform. If you wish to opt out of these websites analysis tools, you may do so by contacting us at&nbsp;<a style='box-sizing: border-box; color: #ff295f; text-decoration-line: none; background-color: transparent; touch-action: manipulation;' href='mailto:support@lifeloop.live'>support@lifeloop.live</a></p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.5.</span>&nbsp;For our members' enjoyment and convenience, we also use 'cookies' to allow you to enter your password less frequently during a session and to provide for easier registration. If you configure your browser or choose to reject the cookies, you may still use our site. To best experience our website and our Platform you must have cookies enabled.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>1.6.</span>&nbsp;We do not collect information from any person under 13 years of age.</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>2. USE OF INFORMATION</h4>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>2.1.</span>&nbsp;We use the information that we collect about you (to include your personally identifiable information) to create a more personalized experience for you, the user. This enhanced user experience is based upon your individual usage habits your personal information. We do not use any data postings, conversations, materials that is provided during individual group sessions within the Platform.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>2.2.</span>&nbsp;We may compile the data that we collect about you and utilize that information, in an aggregate form only for use with various organizations and that are partners associates or collaborators for advertising and/or marketing purposes.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>2.3.</span>&nbsp;We reserve the right to retain and use any photograph or video submitted for publication on the Platform whether via email postings on our website or feedback from group members. Our use of the such material is consistent with the restrictions on disclosure of Personally Identifiable Information. We further reserve to right to monitor, edit and/or restrict any photographs or video that are posted on the platform by an organization, administrator, group leader or user.</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>3. DISCLOSURE OF INFORMATION</h4>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>3.1.</span>&nbsp;Opt out requirement: Without your affirmative consent, we do not sell rent or otherwise share your personally identifiable information with other third parties unless otherwise required as described below under &ldquo;Required Disclosures&rdquo;. Lifeloop.live will only share your data with our partners or advertisers in an aggregate manner, that is not linked to your Personally Identifiable Information. Lifeloop.live will also share data with our partners and advertisers that is non-personally identifiable information.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>3.2.</span>&nbsp;Users should be cognizant that information provided through the registration process or any posts to the public area of our website, or use of the Platform (name/geographical information) may be accessible and made public by search engines, metasearch tools, crawlers, metacrawlers and other similar programs.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>3.3.</span>&nbsp;Lifeloop.live takes your privacy seriously and makes every effort to preserve member privacy. There are some instances where we may need to disclose your Personally Identifiable Information when required by law (Required Disclosure) or if we have a good-faith belief that such disclosure is necessary to comply with a current judicial proceeding, court order or legal process that is served upon our Platform. We will comply with any lawful order that is issued by a law enforcement agency.</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>4. COMMUNICATIONS FROM LIFELOOP.LIVE AND MEMBERS OF THE LIFELOOP.LIVE GROUPS</h4>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>4.1.</span>&nbsp;Lifeloop.live is built around the communities that represent various faith-based churches organizations and entities. An organization that joins Lifeloop.live will appoint an administrator who will then designate 'group leaders'. These group leaders will then create the individual groups and send/receive invites from individuals who are interested in joining the community. Organizations, administrators and group leaders control whether a group is created or closed.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>4.2.</span>&nbsp;Only members of the group will be able to participate and view on-line video group chat/texts, shared documents with in that specific community. A visitor to Lifeloop.live will only be able to see the name of the group, name of the group members, and the faith-based organization that sponsors the group.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>4.3.</span>&nbsp;Members of a group will not necessarily be notified that a new user is added to or delete from the group. Only the organization, administrator,or group leader has the authority to add or delete a user from a group.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>4.4.</span>&nbsp;A user may request to join a group even if that user does not belong or affiliate with the organization that is sponsoring the group.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>4.5.</span>&nbsp;If a user participates in a group on Lifeloop.live, that the user is implicitly granting some control of postings and the privacy of their profile to the organizations, administrators and group leaders.</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>5. EDIT / REVIEW / DEACTIVATION OF PERSONAL INFORMATION</h4>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>5.1.</span>&nbsp;Lifeloop.live allows an organization or user to update their Personally Identifiable Information after their initial registration to the Platform. Upon the request of an organization or user, we will deactivate the account and remove it from our active database. To make this request, email&nbsp;<a style='box-sizing: border-box; color: #ff295f; text-decoration-line: none; background-color: transparent; touch-action: manipulation;' href='mailto:support@lifeloop.live'>support@lifeloop.live</a>&nbsp;Upon receipt of the request we will deactivate the user account as soon as reasonably possible in accordance with our deactivation policy and any applicable law.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>5.2.</span>&nbsp;We will maintain a record of information in our database (back up storage) that you may have requested that we remove that, in our discretion, is necessary for us to resolve any disputes, correct problems or enforce the Terms of Service Agreement. The information is never fully removed due to technical and legal constraints. This information will be encrypted while maintained by Lifeloop.live.</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>6. NOTIFICATION OF CHANGE</h4>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>6.1.</span>&nbsp;If there is a change to this policy we will make notifications on&nbsp;<a style='box-sizing: border-box; color: #ff295f; text-decoration-line: none; background-color: transparent; touch-action: manipulation;' href='http://lifeloop.live/privacy'>http://lifeloop.live/privacy</a>&nbsp;or post notice of the changes to the Policy on the homepage (<a style='box-sizing: border-box; color: #ff295f; text-decoration-line: none; background-color: transparent; touch-action: manipulation;' href='http://lifeloop.live/'>http://lifeloop.live/</a>) and in any other fashion that we deem appropriate. This notification of change is to allow the organizations and users of the Platform to always know how we collect, store, use and disclose information. We will use information in accordance with the Privacy Policy statement under which this information was collected.</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>7. DISPUTE RESOLUTION</h4>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'><span style='box-sizing: border-box; font-weight: bolder;'>7.1.</span>&nbsp;Any dispute, claim or controversy that arises from the use of the Platform or this Policy or previous Privacy Policy statements shall be resolved through negotiation, mediation and arbitration as provided under our Terms of Service Agreement.</p>
                    <h4 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 1.5rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>8. CONTACT INFORMATION</h4>
                    <p class='mb-5' style='box-sizing: border-box; margin-top: 0px; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif; margin-bottom: 3rem !important;'>Toneo, Inc.<br style='box-sizing: border-box;' />22211 IH 10 West, Suite 1206<br style='box-sizing: border-box;' />San Antonio, TX 78257</p>
                   """,
        'pagetype': 'privacy',
        'updated_by': 'test@email.com'},
        {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'title': "<h2 class='mt-5' style='box-sizing: border-box; margin-top: 3rem !important; margin-bottom: 0.5rem; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial;'>TERMS &amp; CONDITIONS</h2>",
        'content': """
                    <p class='mt-3' style='box-sizing: border-box; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif; margin-top: 1rem !important;'>Please read these Terms and Conditions ('Terms', 'Terms and Conditions') carefully before using the www.lifeloop.live website (the 'Service') operated by Toneo, LLC doing business as LiveLoop.Live ('us', 'we', or 'our').</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who wish to access or use the Service.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you do not have permission to access the Service.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>COMMUNICATIONS</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>By creating an Account on our service, you agree to subscribe to newsletters, marketing or promotional materials and other information we may send. However, you may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Create an account, designate an administrator, grant leader privileges, create sessions, and your team is up and connecting in no time.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>PURCHASES</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>If you wish to purchase any product or service made available through the Service ('Purchase'), you may be asked to supply certain information relevant to your Purchase including, without limitation, your credit card number, the expiration date of your credit card, your billing address, and your shipping information.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You represent and warrant that: (i) you have the legal right to use any credit card(s) or other payment method(s) in connection with any Purchase; and that (ii) the information you supply to us is true, correct and complete.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>The service may employ the use of third party services for the purpose of facilitating payment and the completion of Purchases. By submitting your information, you grant us the right to provide the information to these third parties subject to our Privacy Policy.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We reserve the right to refuse or cancel your order at any time for reasons including but not limited to: product or service availability, errors in the description or price of the product or service, error in your order or other reasons.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We reserve the right to refuse or cancel your order if fraud or an unauthorized or illegal transaction is suspected.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>AVAILABILITY, ERRORS AND INACCURACIES</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We are constantly updating product and service offerings on the Service. We may experience delays in updating information on the Service and in our advertising on other web sites. The information found on the Service may contain errors or inaccuracies and may not be complete or current. Products or services may be mispriced, described inaccurately, or unavailable on the Service and we cannot guarantee the accuracy or completeness of any information found on the Service.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We therefore reserve the right to change or update information and to correct errors, inaccuracies, or omissions at any time without prior notice.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>CONTESTS, SWEEPSTAKES AND PROMOTIONS</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Any contests, sweepstakes or other promotions (collectively, 'Promotions') made available through the Service may be governed by rules that are separate from these Terms &amp; Conditions. If you participate in any Promotions, please review the applicable rules as well as our Privacy Policy. If the rules for a Promotion conflict with these Terms and Conditions, the Promotion rules will apply.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>SUBSCRIPTIONS</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Some parts of the Service are billed on a subscription basis ('Subscription(s)'). You will be billed in advance on a recurring and periodic basis ('Billing Cycle'). Billing cycles are set either on a monthly or annual basis, depending on the type of subscription plan you select when purchasing a Subscription.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or Toneo, LLC doing business as LiveLoop.Live cancels it. You may cancel your Subscription renewal either through your online account management page or by contacting Toneo, LLC doing business as LiveLoop.Live customer support team.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>A valid payment method, including credit card, is required to process the payment for your Subscription. You shall provide Toneo, LLC doing business as LiveLoop.Live with accurate and complete billing information including full name, address, state, zip code, telephone number, and a valid payment method information. By submitting such payment information, you automatically authorize Toneo, LLC doing business as LiveLoop.Live to charge all Subscription fees incurred through your account to any such payment instruments.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Should automatic billing fail to occur for any reason, Toneo, LLC doing business as LiveLoop.Live will issue an electronic invoice indicating that you must proceed manually, within a certain deadline date, with the full payment corresponding to the billing period as indicated on the invoice.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>FREE TRIAL</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Toneo, LLC doing business as LiveLoop.Live may, at its sole discretion, offer a Subscription with a free trial for a limited period of time ('Free Trial').</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You may be required to enter your billing information in order to sign up for the Free Trial.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>If you do enter your billing information when signing up for the Free Trial, you will not be charged by Toneo, LLC doing business as LiveLoop.Live until the Free Trial has expired. On the last day of the Free Trial period, unless you cancelled your Subscription, you will be automatically charged the applicable Subscription fees for the type of Subscription you have selected.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>At any time and without notice, Toneo, LLC doing business as LiveLoop.Live reserves the right to (i) modify the terms and conditions of the Free Trial offer, or (ii) cancel such Free Trial offer.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>FEE CHANGES</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Toneo, LLC doing business as LiveLoop.Live, in its sole discretion and at any time, may modify the Subscription fees for the Subscriptions. Any Subscription fee change will become effective at the end of the then-current Billing Cycle.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Toneo, LLC doing business as LiveLoop.Live will provide you with a reasonable prior notice of any change in Subscription fees to give you an opportunity to terminate your Subscription before such change becomes effective.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Your continued use of the Service after the Subscription fee change comes into effect constitutes your agreement to pay the modified Subscription fee amount.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>REFUNDS</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Certain refund requests for Subscriptions may be considered by Toneo, LLC doing business as LiveLoop.Live on a case-by-case basis and granted in sole discretion of Toneo, LLC doing business as LiveLoop.Live.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>CONTENT</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material ('Content'). You are responsible for the Content that you post on or through the Service, including its legality, reliability, and appropriateness.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>By posting Content on or through the Service, You represent and warrant that: (i) the Content is yours (you own it) and/or you have the right to use it and the right to grant us the rights and license as provided in these Terms, and (ii) that the posting of your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. We reserve the right to terminate the account of anyone found to be infringing on a copyright.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You retain any and all of your rights to any Content you submit, post or display on or through the Service and you are responsible for protecting those rights. We take no responsibility and assume no liability for Content you or any third party posts on or through the Service. However, by posting Content using the Service you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service. You agree that this license includes the right for us to make your Content available to other users of the Service, who may also use your Content subject to these Terms.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Toneo, LLC doing business as LiveLoop.Live has the right but not the obligation to monitor and edit all Content provided by users.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>In addition, Content found on or through this Service are the property of Toneo, LLC doing business as LiveLoop.Live or used with permission. You may not distribute, modify, transmit, reuse, download, repost, copy, or use said Content, whether in whole or in part, for commercial purposes or for personal gain, without express advance written permission from us.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>ACCOUNTS</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>When you create an account with us, you guarantee that you are above the age of 18, and that the information you provide us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on the Service.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You are responsible for maintaining the confidentiality of your account and password, including but not limited to the restriction of access to your computer and/or account. You agree to accept responsibility for any and all activities or actions that occur under your account and/or password, whether your password is with our Service or a third-party service. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you, without appropriate authorization. You may not use as a username any name that is offensive, vulgar or obscene.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in our sole discretion.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>COPYRIGHT POLICY</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted on the Service infringes on the copyright or other intellectual property rights ('Infringement') of any person or entity.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>If you are a copyright owner, or authorized on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright infringement, please submit your claim via email to&nbsp;<a style='box-sizing: border-box; color: #ff295f; text-decoration-line: none; background-color: transparent; touch-action: manipulation;' href='mailto:support@lifeloop.live'>support@lifeloop.live</a>&nbsp;with the subject line: 'Copyright Infringement' and include in your claim a detailed description of the alleged Infringement as detailed below, under 'DMCA Notice and Procedure for Copyright Infringement Claims'</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You may be held accountable for damages (including costs and attorneys' fees) for misrepresentation or bad-faith claims on the infringement of any Content found on and/or through the Service on your copyright.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>DMCA NOTICE AND PROCEDURE FOR COPYRIGHT INFRINGEMENT CLAIMS</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</p>
                    <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>
                    <li style='box-sizing: border-box;'>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright's interest</li>
                    <li style='box-sizing: border-box;'>A description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work</li>
                    <li style='box-sizing: border-box;'>Identification of the URL or other specific location on the Service where the material that you claim is infringing is located</li>
                    <li style='box-sizing: border-box;'>Your address, telephone number, and email address</li>
                    <li style='box-sizing: border-box;'>A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law</li>
                    <li style='box-sizing: border-box;'>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf</li>
                    </ul>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You can contact our Copyright Agent via email at&nbsp;<a style='box-sizing: border-box; color: #ff295f; text-decoration-line: none; background-color: transparent; touch-action: manipulation;' href='mailto:support@lifeloop.live'>support@lifeloop.live</a></p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>INTELLECTUAL PROPERTY</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of Toneo, LLC doing business as LiveLoop.Live and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Toneo, LLC doing business as LiveLoop.Live.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>LINKS TO OTHER WEB SITES</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Our Service may contain links to third party web sites or services that are not owned or controlled by Toneo, LLC doing business as LiveLoop.Live.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Toneo, LLC doing business as LiveLoop.Live has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You acknowledge and agree that Toneo, LLC doing business as LiveLoop.Live shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such third party web sites or services.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We strongly advise you to read the terms and conditions and privacy policies of any third party web sites or services that you visit.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>TERMINATION</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>If you wish to terminate your account, you may simply discontinue using the Service.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>INDEMNIFICATION</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>You agree to defend, indemnify and hold harmless Toneo, LLC doing business as LiveLoop.Live and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms, or c) Content posted on the Service.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>LIMITATION OF LIABILITY</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>In no event shall Toneo, LLC doing business as LiveLoop.Live, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>DISCLAIMER</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Your use of the Service is at your sole risk. The Service is provided on an 'AS IS' and 'AS AVAILABLE' basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Toneo, LLC doing business as LiveLoop.Live its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>GOVERNING LAW</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>These Terms shall be governed and construed in accordance with the laws of Texas, United States, without regard to its conflict of law provisions.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>CHANGES</h2>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
                    <p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif;'>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.</p>
                    <h2 class='mt-5 mb-3' style='box-sizing: border-box; font-family: Montserrat, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.2; color: #212529; font-size: 2rem; text-transform: uppercase; margin-top: 3rem !important; margin-bottom: 1rem !important;'>CONTACT US</h2>
                    <p class='mb-5' style='box-sizing: border-box; margin-top: 0px; color: #212529; font-family: Montserrat, Helvetica, Arial, sans-serif; margin-bottom: 3rem !important;'>If you have any questions about these Terms, please&nbsp;<a style='box-sizing: border-box; color: #ff295f; text-decoration-line: none; background-color: transparent; touch-action: manipulation;' href='https://lifeloop.live/contact'>contact us</a>.</p>
                   """,
        'pagetype': 'terms',
        'updated_by': 'test@email.com'}])



def downgrade():
    print("Downgrades not supported")
