"""update age_ranges table contents

Revision ID: 314e77a901e4
Revises: 8caf035d7fea
Create Date: 2017-09-19 21:13:20.694575

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
import lifeloopweb.db.utils
from sqlalchemy.dialects import mysql

from sqlalchemy.sql import table, column
from sqlalchemy import String, Binary, Integer



# revision identifiers, used by Alembic.
revision = '314e77a901e4'
down_revision = '8caf035d7fea'
branch_labels = None
depends_on = None


age_ranges = table(
    'age_ranges',
    column('id', Binary),
    column('priority', Integer),
    column('description', String))




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(age_ranges.update().where(age_ranges.c.description == 'Any Age: 13+').values(description='Any Age'))
    op.bulk_insert(age_ranges,
    [
    {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 150,
        'description': 'Teens'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 175,
        'description': 'Young Adults'}
    ])
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
