"""modify group types

Revision ID: 574413882d2b
Revises: 113a4dfd7067
Create Date: 2017-10-02 10:20:47.296352

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
import lifeloopweb.db.utils
from sqlalchemy.dialects import mysql

from sqlalchemy.sql import table, column
from sqlalchemy import String, Binary, Integer

# revision identifiers, used by Alembic.
revision = '574413882d2b'
down_revision = '113a4dfd7067'
branch_labels = None
depends_on = None

group_types = table(
    'group_types',
    column('id', Binary),
    column('priority', Integer),
    column('description', String))

groups = table(
    'groups',
    column('group_type_id', Binary))



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(groups.update().values(group_type_id=None))
    conn.execute(group_types.delete())
    op.bulk_insert(group_types,
    [
    {'id': lifeloopweb.db.utils.generate_guid().bytes,
          'priority': 100,
          'description': 'Accountability'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 200,
        'description': 'Addiction'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 300,
        'description': 'Bereavement'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 400,
        'description': 'Bible Study'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 500,
        'description': 'Career & Workplace'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 600,
        'description': 'Counseling'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 700,
        'description': 'Discipling & Mentoring'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 800,
        'description': 'Education & Training'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 900,
        'description': 'Fellowship'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1000,
        'description': 'Financial & Wealth'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1100,
        'description': 'Get to Know Us'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1200,
        'description': 'Health Related'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1300,
        'description': 'Life Coaching & Guidance'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1400,
        'description': 'Marital'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1500,
        'description': 'Military'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1600,
        'description': 'Ministry Collaboration'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1700,
        'description': 'Missions'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1800,
        'description': 'New Believers'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 1900,
        'description': 'Parenting'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 2000,
        'description': 'Prayer'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 2100,
        'description': 'Pre-Marital'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 2200,
        'description': 'Question & Answer'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 2300,
        'description': 'Single Life'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 2400,
        'description': 'Support'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 2500,
        'description': 'Volunteer'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': 2600,
        'description': 'Other'}
    ])
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
