"""add cohost flag to group member

Revision ID: 691e6ed74b18
Revises: c2b920fbb456
Create Date: 2017-10-15 21:55:56.507884

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '691e6ed74b18'
down_revision = 'dd4ec5efab3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('can_cohost_meeting', sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
