"""Flag for org member to manage subscriptions

Revision ID: 702606797886
Revises: 6da65a033f4e
Create Date: 2018-01-18 05:35:38.472701

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '702606797886'
down_revision = 'acb797ccbc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('can_manage_subscription', sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
