"""add privacy and terms agreed datetime to user model

Revision ID: 938703e6665d
Revises: ae9aa6295100
Create Date: 2017-12-22 13:40:59.409004

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '938703e6665d'
down_revision = 'ae9aa6295100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privacy_and_terms_agreed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
