"""Add column to organization to show address

Revision ID: aa51a9aacd00
Revises: 702606797886
Create Date: 2018-04-02 23:16:42.317993

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa51a9aacd00'
down_revision = '702606797886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('show_address', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
