"""drop image columns from user and group

Revision ID: ae9aa6295100
Revises: 64a90fa34d30
Create Date: 2017-12-22 13:35:52.070652

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae9aa6295100'
down_revision = '64a90fa34d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'main_image_url')
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
