"""empty message

Revision ID: aef05d715e7c
Revises:
Create Date: 2017-04-19 20:03:55.158390

"""
import uuid
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Binary, Integer

import lifeloopweb.db.models
import lifeloopweb.db.utils


# revision identifiers, used by Alembic.
revision = 'aef05d715e7c'
down_revision = None
branch_labels = None
depends_on = None

notification_types = table(
    'notification_types',
    column('id', Binary),
    column('priority', Integer),
    column('description', String))

organization_roles = table(
    'organization_roles',
    column('id', Binary),
    column('priority', Integer),
    column('description', String))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('addresses',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('street_address', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('zip_code', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('age_ranges',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_privacy_settings',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_roles',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_types',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('link_types',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('meet_time_types',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('notification_types',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True, autoincrement=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('organization_job_titles',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('organization_roles',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('zoom_user_id', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('opt_in_texts', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('super_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('app_errors',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('page_name', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ex_message', sa.Text(), nullable=True),
    sa.Column('ex_inner_exception', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('contact_requests',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('groups',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('main_image_url', sa.String(length=500), nullable=True),
    sa.Column('tag_line', sa.String(length=80), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('age_range_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('gender_focus', sa.String(length=80), nullable=True),
    sa.Column('privacy_setting_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('group_type_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['age_range_id'], ['age_ranges.id'], ),
    sa.ForeignKeyConstraint(['group_type_id'], ['group_types.id'], ),
    sa.ForeignKeyConstraint(['privacy_setting_id'], ['group_privacy_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('organizations',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('vanity_name', sa.String(length=80), nullable=True),
    sa.Column('service_times_description', sa.String(length=80), nullable=True),
    sa.Column('date_established', sa.DateTime(), nullable=True),
    sa.Column('address_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user_activities',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('activity_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_documents',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('friendly_name', sa.String(length=80), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_meet_times',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('meet_time_type_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['meet_time_type_id'], ['meet_time_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_members',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('role_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['group_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_notes',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('note_content', sa.Text(), nullable=False),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('images',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
	sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('organization_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user_images',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('image_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_images',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('image_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('organization_images',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('organization_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('image_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('links',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('link_type_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('icon_css_class', sa.String(length=120), nullable=True),
    sa.Column('organization_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['link_type_id'], ['link_types.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('notification_type_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('user_from_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('user_to_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('organization_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('acknowledge_only', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.DateTime(), nullable=True),
    sa.Column('declined', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('organization_groups',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('organization_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('organization_members',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('organization_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('role_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['organization_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('organization_staffs',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('staff_name', sa.String(length=80), nullable=False),
    sa.Column('organization_job_title_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('organization_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['organization_job_title_id'], ['organization_job_titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('zoom_meetings',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('meeting_time', sa.DateTime(), nullable=False),
    sa.Column('repeat_type', sa.String(length=10), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('start_url', sa.String(length=500), nullable=False),
    sa.Column('join_url', sa.String(length=500), nullable=False),
    sa.Column('repeat_end_date', sa.Date(), nullable=True),
    sa.Column('user_id', lifeloopweb.db.models.GUID(length=16), nullable=False),
    sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True),
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_unique_constraint('group_user_membership', 'group_members', ['group_id', 'user_id'])
    op.create_unique_constraint('org_user_membership', 'organization_members', ['organization_id', 'user_id'])
    op.execute(notification_types.delete())
    op.bulk_insert(notification_types,
                   [
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 100,
                        'description': 'Invitation to Join Group'},
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 200,
                        'description': 'Group Join Request'},
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 300,
                        'description': 'Invitation to Join Organization'},
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 400,
                        'description': 'Organization Join Request'},
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 500,
                        'description': 'Organization Role Change'},
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 600,
                        'description': 'Group Role Change'},
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 700,
                        'description': 'Organization Creation Request'}
                   ])
    op.bulk_insert(organization_roles,
                   [
                       {'id': lifeloopweb.db.utils.generate_guid().bytes,
                        'priority': 300,
                        'description': 'Group Administrator'}
                   ])
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
