"""add group_id to links

Revision ID: b6266456c314
Revises: 574413882d2b
Create Date: 2017-10-02 15:09:29.114058

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
import lifeloopweb.db.utils
from sqlalchemy.dialects import mysql

from sqlalchemy.sql import table, column
from sqlalchemy import String, Binary, Integer

# revision identifiers, used by Alembic.
revision = 'b6266456c314'
down_revision = 'e5e8cfb40205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('group_id', lifeloopweb.db.models.GUID(length=16), nullable=True))
    op.create_foreign_key("fk_groups_links", "links", "groups", ["group_id"], ["id"])
    # # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
