"""Add new link types

Revision ID: c2b920fbb456
Revises: b6266456c314
Create Date: 2017-10-11 14:02:36.456575

"""
import uuid
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Binary, Integer

import lifeloopweb.db.models
import lifeloopweb.db.utils

# revision identifiers, used by Alembic.
revision = 'c2b920fbb456'
down_revision = 'b6266456c314'
branch_labels = None
depends_on = None

link_types = table(
    'link_types',
    column('id', Binary),
    column('description', String))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(link_types,
    [
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'description': 'Instagram'},
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'description': 'Other'}
    ])
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
