"""add duration to zoom meeting

Revision ID: d5f7c5fcb910
Revises: 574413882d2b
Create Date: 2017-10-03 21:28:03.169664

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5f7c5fcb910'
down_revision = '574413882d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_staffs')
    op.drop_table('app_errors')
    op.drop_table('organization_job_titles')
    op.drop_table('contact_requests')
    op.drop_table('user_activities')
    op.drop_table('activities')
    op.add_column('zoom_meetings', sa.Column('duration', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
