"""Add Creator to organization_roles

Revision ID: dd4ec5efab3d
Revises: c2b920fbb456
Create Date: 2017-10-12 13:35:06.883742

"""
import uuid
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Binary, Integer

import lifeloopweb.db.models
import lifeloopweb.db.utils

# revision identifiers, used by Alembic.
revision = 'dd4ec5efab3d'
down_revision = 'c2b920fbb456'
branch_labels = None
depends_on = None

org_roles = table(
    'organization_roles',
    column('id', Binary),
    column('priority', Integer),
    column('description', String))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(org_roles,
    [
      {'id': lifeloopweb.db.utils.generate_guid().bytes,
        'priority': '350',
        'description': 'Group Creator'}
    ])
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
