"""add member_limit column

Revision ID: e5e8cfb40205
Revises: d5f7c5fcb910
Create Date: 2017-10-10 12:50:40.053019

"""
from alembic import op
import sqlalchemy as sa

import lifeloopweb.db.models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5e8cfb40205'
down_revision = 'd5f7c5fcb910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('member_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    print("Downgrades not supported")
