import os


TEST_ENV = {
    "ALLOWED_FILE_EXTENSIONS": "txt,pdf,doc,docx,xls,xlsx,ppt,pptx",
    "ALLOWED_VIDEO_EXTENSIONS": "mpg,mp2,mpeg,mpe,mpv,webm,ogg,mp4,m4p,m4v,mov",
    "AWS_ACCESS_KEY_ID": "aws_access_key",
    "AWS_SECRET_ACCESS_KEY": "aws_secret_access_key",
    "AWS_BUCKET_NAME": "aws_bucket_name",
    "ALLOWED_IMAGE_EXTENSIONS": "jpg,png,jpeg,gif",
    "CHARGIFY_API_KEY": "chargify_api_key",
    "CHARGIFY_DEFAULT_COMPONENT_ID": "1",
    "CHARGIFY_REQUEST_URL": "chargify_request_url",
    "CLOUDINARY_API_KEY": "cloudinary_api_key",
    "CLOUDINARY_SECRET": "cloudinary_secret",
    "CLOUDINARY_CLOUD_NAME": "cloudinary_cloud_name",
    "CLOUDINARY_UPLOAD_PRESET": "cloudinary_upload_preset",
    "CSRF_SECRET_KEY": "Ar3Iz#CEh@#zlYsr7q3KnsLc72oaCx!w",
    "DATABASE_CONNECTION_POOLSIZE": "20",
    "DATABASE_CONNECTION_OVERFLOWPOOL": "20",
    "DATABASE_CONNECTION_POOLRECYCLE": "3600",
    "DATABASE_CONNECTION_DEBUG": "False",
    "DB_ENGINE_URL":
        "mysql+pymysql://root:@database/lifeloopweb_test?charset=utf8",
    "DISQUS_PUBLIC_KEY": "disqus_public_key",
    "DISQUS_SECRET_KEY": "disqus_secret_key",
    "DISQUS_SITE_NAME": "disqus_site_name",
    "EMAIL_DRIVER": "SendmailDriver",
    "EMAIL_HOST": "mailhog",
    "EMAIL_MAILFROM": "noreply@lifeloop.live",
    "EMAIL_PORT": "1025",
    "ENVIRONMENT": "test",
    "FLASK_STATIC_FOLDER": "build",
    "GOOGLE_ANALYTICS_ID": "google_analytics_id",
    "GOOGLE_ANALYTICS_KEY_FILE_LOCATION": "google_analytics_key_file_location",
    "GOOGLE_ANALYTICS_PRIVATE_KEY_ID": "google_analytics_private_key_id",
    "GOOGLE_ANALYTICS_PRIVATE_KEY": "google_analytics_private_key",
    "GOOGLE_ANALYTICS_VIEW_ID": "google_analytics_view_id",
    "GOOGLE_API_KEY": "google_api_key",
    "GOOGLE_API_CLIENT_ID": "google_api_client_id",
    "LLW_ORG_ID": "llw_org_id",
    "LOG_FILE_PATH": "lifeloop-{}.log",
    "LOGGING_ADMINS": "jason@meridth.io",
    "LOGGING_ERROR_EMAIL_FROM": "server-error@lifeloop.live",
    "LOGGING_ERROR_EMAIL_LEVEL": "ERROR",
    "LOGLEVEL": "DEBUG",
    "MAILGUN_API_KEY": "mailgun_api_key",
    "MAILGUN_DOMAIN": "mailgun_domain",
    "MAX_GROUPS_ON_HOMEPAGE": "40",
    "MEETING_DRIVER": "ZoomMeetingDriver",
    "ORCAWAVE_API_KEY": "orcawave_api_key",
    "ORCAWAVE_SECRET": "orcawave_secret",
    "ORCAWAVE_PHONE_NUMBER1": "orcawave_phone_number1",
    "ORCAWAVE_PHONE_NUMBER2": "orcawave_phone_number2",
    "ORCAWAVE_PHONE_NUMBER3": "orcawave_phone_number3",
    "RECAPTCHA_ENABLED": True,
    "RECAPTCHA_SITE_KEY": "recaptcha_site_key",
    "RECAPTCHA_SECRET_KEY": "recaptcha_secret_key",
    "RECAPTCHA_THEME": "recaptcha_theme",
    "RECAPTCHA_TYPE": "recaptcha_type",
    "RECAPTCHA_SIZE": "recaptcha_size",
    "RECAPTCHA_TABINDEX": "0",
    "SENTRY_DSN": "sentry_dsn",
    "SENTRY_USER_ATTRS": "first_name,last_name,email",
    "SIGNING_SECRET_KEY": "secret-test-key",
    "SITE_DOMAIN": "http://127.0.0.1:5000",
    "SMS_DRIVER": "OrcaWaveDriver",
    "SUBSCRIPTION_DRIVER": "subscription_driver",
    "SUBSCRIPTION_OLD_USERS_WEEK_STARTS": "1",
    "SUCCESS_FLASH_TIMEOUT_IN_SECONDS": "10",
    "SUPPORT_EMAIL_ADDRESS": "support@lifeloop.live",
    "TOKEN_EXPIRES_IN_DAYS": "3",
    "TOKEN_EXPIRES_IN_HOURS": "3",
    "USER_MINYEARS": "16",
    "WEBPACK_MANIFEST_PATH": "build/manifest.json",
    "ZOOM_API_KEY": "zoom_api_key",
    "ZOOM_API_SECRET": "zoom_api_secret",
    "ZOOM_API_TOKEN": "zoom_api_token",
    "ZOOM_HOST_USER_ID": "zoom_host_user_id",
}

for k, v in TEST_ENV.items():
    os.environ.setdefault(k, str(v))
